const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';
const USER_ID_IS_REQUIRED = 'USER_ID_IS_REQUIRED';
const USER_TOKEN_IS_REQUIRED = 'USER_TOKEN_IS_REQUIRED';
const USER_IS_EXIST = 'USER_IS_EXIST';
const NO_AVATAR = 'NO_AVATAR';

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ID_IS_REQUIRED,
    USER_TOKEN_IS_REQUIRED,
    USER_IS_EXIST,
    NO_AVATAR
}